### ISSUE TITLE
pip install ERROR

### ISSUE THREAD

**Issue by Shijie97** [thunlp/ConceptFlow#11]
In requirements.txt saying:
torch==1.3.0.post2
torchvision==0.4.1.post2

However, errors happend as follows:
ERROR: Could not find a version that satisfies the requirement torch==1.3.0.post2 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.3.0.post2

ERROR: Could not find a version that satisfies the requirement torchvision==0.4.1.post2 (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.3.0, 0.4.1, 0.5.0)
ERROR: No matching distribution found for torchvision==0.4.1.post2

What is the correct version?

**Comment by HouyuZhang1007** [comment]
Sorry for the inconvenience.

I guess the reason for this error is this environment is for Mac OS. Since our previous Linux system is down, we are not able to export a Linux environment at this moment. However, we'll upload the environment for Linux as soon as it's fixed.

**Comment by Shijie97** [comment]
Thank you very much. It does help me a lot. Now I'd try other version to see if it is suitable for Linux.
