### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by liulangmagong** [thunlp/ConceptFlow#12]
数据集太大了，对于我的电脑来说(16G内存，GTX1660Ti(6g))，该如何处理数据来更好的将数据读入呢

**Comment by EdwardZH** [comment]
我觉得你应该使用服务器来跑，或者自行修改下data loader

**Comment by liulangmagong** [comment]
非常感谢您的回信，接下来会多做一些尝试的


| |
王世洋
邮箱：17854250704@163.com
|

签名由 网易邮箱大师 定制

On 09/25/2020 18:17, EdwardZH wrote:

我觉得你应该使用服务器来跑，或者自行修改下data loader

**Comment by liulangmagong** [comment]
麻烦问一下，这个数据集用什么配置的服务器基本跑起来就没有问题了？


| |
王世洋
邮箱：17854250704@163.com
|

签名由 网易邮箱大师 定制

On 09/25/2020 20:46, 王世洋 wrote:
非常感谢您的回信，接下来会多做一些尝试的


| |
王世洋
邮箱：17854250704@163.com
|

签名由 网易邮箱大师 定制

On 09/25/2020 18:17, EdwardZH wrote:

我觉得你应该使用服务器来跑，或者自行修改下data loader
