### ISSUE TITLE
Inconsistency between paper and code

### ISSUE THREAD

**Issue by zhongpeixiang** [thunlp/ConceptFlow#2]
Hi, 

In the paper (Eq. 20 in appendix A), relation embedding ``r`` has dim of ``trans_units`` but ``p`` is initialized from ``h_m`` in ``H`` (Eq. 1) and has dim of ``units``, how to compute the dot product between them?

However, in the code (https://github.com/thunlp/ConceptFlow/blob/31bd5eb63c82a5f774872fa092d3f16a16584249/model.py#L146), it seems that ``p`` is initialized from the last  hidden state of a node LSTM instead of ``h_m`` from a text GRU.

**Comment by HouyuZhang1007** [comment]
Thanks for your interest!

Current code and data in this repo are temporary placement for camera-ready. We will release full data and code soon. The paper is also revised for camera-ready, which we'll release later.

**Comment by zhongpeixiang** [comment]
Thanks, looking forward to the final version
