### ISSUE TITLE
How to filter entities from the post?

### ISSUE THREAD

**Issue by wangjs9** [thunlp/ConceptFlow#28]
Hi, thank you for this great work! I have a question about the way to filter entities from the post. In the paper, the example shows that "chat" "based" and "future" are zero-hop concepts for "chat based on knowledge is the future". But how about "knowledge"? I find "knowledge" is also in ConceptNet and is also an entity.

Looking forward to your reply~~

**Comment by HouyuZhang1007** [comment]
Hi, thanks for your interest! The case in figure 1 is an artificial example to illustrate motivation. If you are looking for a real case, figure 4 is extracted from the dataset with attention distributions.

**Comment by wangjs9** [comment]
Thank you! Get it!
