### ISSUE TITLE
Mistakes in training

### ISSUE THREAD

**Issue by xiao-ming-code** [thunlp/ConceptFlow#34]
During the execution of python train.py, there was an error. I think there is no corresponding key in the data. I would like to ask whether there is A problem with my data. How to solve this problem?\

![RO)E{0{91Y$A7H V}LVYMN](https://user-images.githubusercontent.com/73177290/144956886-31d85676-dbf7-4b6b-9eda-650ae44bb0b8.png)
![MRB2X@M1BG %QM@VW}EF84W](https://user-images.githubusercontent.com/73177290/144956894-5a550a8c-0479-46f0-bd50-2306e77314b4.png)

**Comment by HouyuZhang1007** [comment]
closed the ticket. Feel free to re-open it if you still have the issue.
