### ISSUE TITLE
Dataset unzip failed

### ISSUE THREAD

**Issue by SeaEagleI** [thunlp/ConceptFlow#39]
从Google Drive上把10.5G的数据集压缩包下下来后，我用winrar解压trainset.txt文件一直失败，显示checksum error，压缩包中的其他文件没有问题。忽略报错强行解压得到的trainset.txt文件只有367,655行，而且最后一行长这样：
`{"all_ent`
而论文中的数据总量为3,384,185，显然我这里得到的trainset.txt文件是不全的。我又用Google Drive附带的ZIP Extractor和我服务器Ubuntu系统上的unzip工具试了几遍，同样是解压失败。但我看别的issue里没有提到过这个问题，所以可能是最近Google Drive上的data.zip文件损坏了吗？

**Comment by SeaEagleI** [comment]
请问作者大大还有这个压缩包的原始版本吗？恳求再分享一份，万分感谢

**Comment by HouyuZhang1007** [comment]
I just tested uncompressing the data on a mac laptop and it works well. Would you please try on Mac OS? Please don't use unzip cuz I remember it has a limitation of file size of 4GB.
