### ISSUE TITLE
Datasete

### ISSUE THREAD

**Issue by Banana-lwz** [thunlp/ConceptFlow#43]
Hello, thank you for such an excellent work, my research direction is dialogue system, your work is very important to me, could you please send the dataset to my mailbox：wenzhelou@foxmail.com, I would be very grateful!

**Comment by MrGM26** [comment]
> Hello, thank you for such an excellent work, my research direction is dialogue system, your work is very important to me, could you please send the dataset to my mailbox：[wenzhelou@foxmail.com](mailto:wenzhelou@foxmail.com), I would be very grateful!

Hello I have also worked on it. Please check my codes which are also updated.
https://github.com/MrGM26/conceptdialogflow

**Comment by HouyuZhang1007** [comment]
Hi, thanks for your interest. To request dataset, please send an email to craigie.zhang@gmail.com so that we could track the record. Thanks
